# Copyright 2022 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  indico_no_reply_email:
    type: string
    description: Email address used when sending emails to users to which they should not reply.
    default: 'noreply@mydomain.local'
  indico_public_support_email:
    type: string
    description: Email address that is shown to users on the “Contact” page.
    default: 'support@mydomain.local'
  indico_support_email:
    type: string
    description: Email address of the technical manager of the Indico instance.
    default: 'support-tech@mydomain.local'
  site_url:
    type: string
    description: URL through which Indico is accessed by users.
    default: 'http://indico'
  smtp_server:
    type: string
    description: The hostname of the SMTP server used for sending emails.
    default: ''
  smtp_port:
    type: int
    description: The port of the SMTP server used for sending emails.
    default: 25
  smtp_login:
    type: string
    description: The username to send if the SMTP server requires authentication.
    default: ''
  smtp_password:
    type: string
    description: The password to send if the SMTP server requires authentication.
    default: ''
  smtp_use_tls:
    type: boolean
    description: If enabled, STARTTLS will be used to use an encrypted SMTP connection.
    default: true
