name: Publish to edge

# On push to a "special" branch, we:
# * always publish to charmhub at latest/edge/branchname
# * always run tests
# where a "special" branch is one of main/master or track/**, as
# by convention these branches are the source for a corresponding
# charmhub edge channel.

on:
  push:
    branches:
      - master
      - main
      - track/**

jobs:

  tests:
    name: Run Tests
    uses: ./.github/workflows/ci.yaml
    secrets:
      charmhub-token: "${{ secrets.CHARMCRAFT_CREDENTIALS }}"

  release-charm-to-edge:
    name: Publish Charm
    needs: tests
    uses: ./.github/workflows/release.yaml
    secrets:
      charmhub-token: "${{ secrets.CHARMCRAFT_CREDENTIALS }}"