name: Publish

on:
  workflow_call:
    secrets:
      charmhub-token:
        required: true

jobs:
  publish-charm:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo snap install docker
          sudo snap install charmcraft --classic
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Publish image
        env:
          CHARMCRAFT_AUTH: ${{ secrets.charmhub-token }}
        run: |
          docker build . -t indico:latest -f indico.Dockerfile
          SHA=$(docker image ls -q indico:latest)
          charmcraft upload-resource indico indico-image --image=$SHA
      - name: Publish Charm
        env:
          CHARMCRAFT_AUTH: ${{ secrets.charmhub-token }}
        run: |
          charmcraft pack --verbose
          RESOURCE_VERSION=$(expr $(charmcraft resource-revisions indico indico-image | tail -n +2 | sort -nrk1 | head -1 | cut -d ' ' -f1) + 1)
          REVISION=$(expr $(charmcraft revisions indico | tail -n +2 | sort -nrk1 | head -1 | cut -d ' ' -f1) + 1)
          charmcraft release indico --revision=$REVISION --channel=beta --resource=indico-image:$RESOURCE_VERSION
